import { ProductsType } from "./type"

import SS1000 from "../assets/images/bat/ss-1000.png"
import SSton from "../assets/images/bat/ss-ton-gold.png"
import MRFGenius from "../assets/images/bat/MRF-Genius-Grand.png"
import MRFViratKing from "../assets/images/bat/MRF-virat-king.png"
import GNKronus from "../assets/images/bat/GN-kronus.png"
import GNLegend from "../assets/images/bat/GN-legend.png"
import KookaburraGhost from "../assets/images/bat/kookaburra-ghost.png"
import KookaburraKahuna from "../assets/images/bat/kookaburra_kahuna.png"
import SGRSD from "../assets/images/bat/SG-rsd.png"
import SGSunny from "../assets/images/bat/Sg-Sunny.png"
import SGPlayer from "../assets/images/bat/SG_players.png"

export const CricketBats: ProductsType[] = [
  {
    id: 31,
    name: "SS Master 1000",
    type: "English Willow",
    price: 5000,
    rating: 4.2,
    image: SS1000,
    popular: false,
    discount: 10,
    discountPrice: 4500,
    company: "SS",
  },
  {
    id: 32,
    name: "SS Ton Gold",
    type: "Kashmir Willow",
    price: 7000,
    rating: 4.5,
    image: SSton,
    popular: false,
    discount: 15,
    discountPrice: 5950,
    company: "SS",
  },
  {
    id: 33,
    name: "MRF Genius Grand Edition",
    type: "English Willow",
    price: 8000,
    rating: 4.7,
    image: MRFGenius,
    popular: false,
    discount: 12,
    discountPrice: 7040,
    company: "MRF",
  },
  {
    id: 34,
    name: "MRF Virat King",
    type: "Kashmir Willow",
    price: 12000,
    rating: 4.8,
    image: MRFViratKing,
    popular: true,
    discount: 20,
    discountPrice: 9600,
    company: "MRF",
  },
  {
    id: 35,
    name: "Gray-Nicolls Kronus 200",
    type: "English Willow",
    price: 15000,
    rating: 4.6,
    image: GNKronus,
    popular: false,
    discount: 5,
    discountPrice: 14250,
    company: "Gray-Nicolls",
  },
  {
    id: 36,
    name: "Gray-Nicolls Legend",
    type: "English Willow",
    price: 20000,
    rating: 4.9,
    image: GNLegend,
    popular: true,
    discount: 10,
    discountPrice: 18000,
    company: "Gray-Nicolls",
  },
  {
    id: 37,
    name: "Kookaburra Ghost",
    type: "Kashmir Willow",
    price: 10000,
    rating: 4.3,
    image: KookaburraGhost,
    popular: false,
    discount: 8,
    discountPrice: 9200,
    company: "Kookaburra",
  },
  {
    id: 38,
    name: "Kookaburra Kahuna",
    type: "English Willow",
    price: 18000,
    rating: 4.7,
    image: KookaburraKahuna,
    popular: true,
    discount: 12,
    discountPrice: 15840,
    company: "Kookaburra",
  },
  {
    id: 39,
    name: "SG RSD Spark",
    type: "Kashmir Willow",
    price: 4500,
    rating: 4.1,
    image: SGRSD,
    popular: false,
    discount: 5,
    discountPrice: 4275,
    company: "SG",
  },
  {
    id: 300,
    name: "SG Sunny Tonny",
    type: "English Willow",
    price: 8500,
    rating: 4.6,
    image: SGSunny,
    popular: false,
    discount: 10,
    discountPrice: 7650,
    company: "SG",
  },
  {
    id: 301,
    name: "SG Player Edition",
    type: "English Willow",
    price: 12000,
    rating: 4.8,
    image: SGPlayer,
    popular: true,
    discount: 15,
    discountPrice: 10200,
    company: "SG",
  },
]
